"""
core/level.py
Ratchet & Clank: Rift Apart PC — level/zone asset parser.

From ALERT source the level asset type is identified by DAT1 unk1 = 0x2AFE7495.
Zone assets use unk1 = 0x8A0B1487.

These are complex assets with many section types. For RCRA Forge's purposes
we expose enough to show the scene hierarchy and instance placements.

The most relevant sections discovered from ALERT:
  dat1lib/types/sections/level/  — level-specific sections
  dat1lib/types/sections/zone/   — zone sections (autogen.py has many entries)

Since the exact binary layouts of level/zone sections are autogenerated in ALERT
and vary a lot, this module reads what it can and falls back gracefully.
The primary use is to populate the Scene panel with zone names and instance counts.
"""

from __future__ import annotations
import struct
from dataclasses import dataclass, field
from typing import Optional

from core.archive import DAT1, ASSET_TYPE_NAMES

# DAT1 unk1 values for asset types we handle here
ASSET_TYPE_LEVEL  = 0x2AFE7495
ASSET_TYPE_ZONE   = 0x8A0B1487
ASSET_TYPE_CONFIG = 0x21A56F68


@dataclass
class ZoneInfo:
    asset_id: int
    name:     str = ''
    instance_count: int = 0


@dataclass
class LevelInfo:
    asset_type:  str
    version:     int = 0
    zone_ids:    list[int] = field(default_factory=list)
    description: str = ''


@dataclass
class ObjectInstance:
    instance_id: int
    asset_id:    int
    position:    tuple   # (x, y, z)
    flags:       int = 0


@dataclass
class InstanceTable:
    instances: list[ObjectInstance] = field(default_factory=list)


class LevelParser:
    """
    Minimal parser for level/zone DAT1 assets.

    Since ALERT autogenerates most zone section parsers and their formats
    are complex, we parse what we can read reliably and expose it for
    display in the Scene panel.
    """

    def __init__(self, data: bytes):
        self.dat1 = DAT1(data)
        self.asset_type = ASSET_TYPE_NAMES.get(self.dat1.unk1, 'unknown')

    def parse_info(self) -> LevelInfo:
        return LevelInfo(
            asset_type  = self.asset_type,
            description = f"DAT1 asset type: {self.dat1.unk1:#010x} ({self.asset_type})\n"
                          f"Sections: {len(self.dat1.sections)}\n"
                          f"Section tags: {', '.join(f'{t:#010x}' for t in sorted(self.dat1.sections.keys()))}",
        )

    def list_section_tags(self) -> list[int]:
        return sorted(self.dat1.sections.keys())

    def get_section_raw(self, tag: int) -> Optional[bytes]:
        return self.dat1.get_section(tag)
